name: 'publish_tauri_app'

on:
  push:
    branches:
      - tauri-app_build_action
  workflow_dispatch:

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        settings:
          #- platform: 'macos-latest' # for Arm based macs (M1 and above).
          #  args: '--target aarch64-apple-darwin'
          #- platform: 'macos-latest' # for Intel based macs.
          #  args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-22.04'
            args: ''
          #- platform: 'windows-latest'
          #  args: ''

    runs-on: ${{ matrix.settings.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: install dependencies (ubuntu only)
        if: matrix.settings.platform == 'ubuntu-22.04' # This must match the platform value defined above.
        run: |
            sudo apt-get update
            sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
          # webkitgtk 4.0 is for Tauri v1 - webkitgtk 4.1 is for Tauri v2.
          # You can remove the one that doesn't apply to your app to speed up the workflow a bit.

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.settings.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: install deps
        run: yarn add -D @tauri-apps/cli && yarn install
          
      - name: install frontend dependencies
        # If you don't have `beforeBuildCommand` configured you may want to build your frontend here too.
        # run: yarn install # change this to npm or pnpm depending on which one you use.
        run: yarn tauri build ${{ matrix.settings.args }}
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
        with:
          tauriScript: true
          tagName: cyb-tauri-${{ github.sha }}
          releaseName: 'Cyb standalone app ${{ github.sha }}'
          releaseBody: 'See the assets to install this version.'
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.settings.args }}
